---
- name: Remove malformed or old Docker apt source list
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Remove old Docker apt key file if exists
  file:
    path: /etc/apt/trusted.gpg.d/docker.asc
    state: absent

- name: Remove old Docker apt source list with deprecated name
  file:
    path: "/etc/apt/sources.list.d/download_docker_com_linux_{{ ansible_distribution | lower }}.list"
    state: absent





- name: Ensure apt cache is updated
  apt:
    update_cache: yes
  changed_when: false

- name: Install prerequisites and dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Ensure keyring directory exists
  file:
    path: "{{ docker_keyring_path | dirname }}"
    state: directory
    mode: "0755"

- name: Download Docker GPG key to keyring file
  get_url:
    url: "{{ docker_key_url }}"
    dest: "{{ docker_keyring_path }}"
    mode: '0644'
  register: docker_gpg

- name: Add Docker APT repository (keyring method)
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    filename: docker
    update_cache: yes

- name: Update apt cache after adding Docker repo
  apt:
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Ensure Docker service is enabled and started
  systemd:
    name: "{{ docker_service_name }}"
    enabled: yes
    state: started
  notify: Restart Docker

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
