---
- name: Remove malformed or old Docker apt source list
  file:
    path: /etc/apt/sources.list.d/docker.list
    state: absent

- name: Remove old Docker keyring from /usr/share/keyrings
  file:
    path: "{{ docker_keyring_path }}"
    state: absent

- name: Remove old Docker keyring from /etc/apt/keyrings
  file:
    path: "/etc/apt/keyrings/docker.asc"
    state: absent


- name: Remove old Docker apt source list with deprecated name
  file:
    path: "/etc/apt/sources.list.d/download_docker_com_linux_{{ ansible_distribution | lower }}.list"
    state: absent

- name: Ensure apt cache is updated
  apt:
    update_cache: yes
  changed_when: false

- name: Install prerequisites and dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
- name: Ensure keyring directory exists
  file:
    path: "{{ docker_keyring_path | dirname }}"
    state: directory
    mode: "0755"

- name: Download Docker GPG key (ASCII)
  get_url:
    url: "{{ docker_key_url }}"
    dest: /tmp/docker.gpg
    mode: '0644'

- name: Convert Docker GPG key to GPG binary format
  command: "gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg /tmp/docker.gpg"
  args:
    creates: /usr/share/keyrings/docker-archive-keyring.gpg

- name: Remove temporary Docker GPG key
  file:
    path: /tmp/docker.gpg
    state: absent

- name: Add Docker APT repository (keyring method)
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present
    filename: docker
    update_cache: yes

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: yes

- name: Ensure Docker service is enabled and started
  systemd:
    name: "{{ docker_service_name }}"
    enabled: yes
    state: started
  notify: Restart Docker

- name: Add user to docker group
  user:
    name: "{{ ansible_ssh_user | default('ubuntu') }}"
    groups: docker
    append: yes
