---
- name: Generate kubeadm config file
  template:
    src: kubeadm-config.yaml.j2
    dest: /tmp/kubeadm-config.yaml

- name: Initialize Kubernetes control plane
  command: kubeadm init --config=/tmp/kubeadm-config.yaml
  register: kubeadm_init_output
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu
    group: ubuntu
    mode: 0644

- name: Fetch admin.conf from master node to Ansible controller
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kube_config_path }}"
    flat: yes

- name: Install Calico CNI
  shell: |
    export KUBECONFIG=/etc/kubernetes/admin.conf
    curl https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml -o /tmp/calico.yaml
    kubectl apply -f /tmp/calico.yaml
  args:
    executable: /bin/bash
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: Extract kubeadm join command
  shell: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Save join command to file
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/kubeadm_join_cmd.sh
    mode: 0700

- name: Fetch kubeadm join script to controller
  fetch:
    src: /tmp/kubeadm_join_cmd.sh
    dest: "{{ kubeadm_join_cmd_path }}"
    flat: yes



