apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployName }}
  namespace: {{ include "namespaceName" . }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      containers:
        - name: {{ .Values.containerName }}
          image: {{ .Values.image }}
          ports: 
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          resources:
            requests: 
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "spring-app.labels" . | nindent 18 }}
              topologyKey: kubernetes.io/hostname

