apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ include "namespaceName" . }}
  labels:{{- include "spring-app.labels" . | nindent 4 }}
    
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      imagePullSecrets: 
        - name: {{ .Values.imagePullSecretName | quote }}
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.image }}
          ports: 
            - containerPort: {{ .Values.deployment.service.targetPort }}
              protocol: TCP
          env:
          - name: MONGO_HOST
            value: "mongo-svc"  
          - name: MONGO_PORT
            value: "27017"
          - name: MONGO_DATABASE
            value: "devopsdb"
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USERNAME
            value: "rabbitmq"
          - name: RABBITMQ_PASSWORD
            value: "rabbitmq"
          - name: RABBITMQ_VHOST
            value: "/"
          - name: MEMCACHED_SERVERS
            value: "memcached:11211"
          resources:
            requests: 
              memory: {{ .Values.deployment.resources.requests.memory }}
              cpu: {{ .Values.deployment.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.resources.limits.memory }}
              cpu: {{ .Values.deployment.resources.limits.cpu }}


