apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init-job
  namespace: {{ include "namespaceName" . }}
  labels:
    app: mongo-init
    {{- include "spring-app.labels" . | nindent 4 }}
spec:  
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-mongo
        image: busybox
        command: ['sh', '-c']
        args:
          - |
            for i in 0 1 2; do
              until nc -z -w 2 {{ .Values.StatefulSet.name }}-$i.{{ .Values.StatefulSet.service.name }}.{{ include "namespaceName" . }}.svc.cluster.local 27017; do
                echo "Waiting for mongo pod $i..."
                sleep 2
              done
            done
            echo "All MongoDB pods are up."
      containers:
      - name: mongo-init
        image: {{ .Values.StatefulSet.image }}
        command: ["mongo"]
        args:
          - "--host"
          - "{{ .Values.StatefulSet.name}}-0.{{ .Values.StatefulSet.service.name }}.{{ include "namespaceName" . }}.svc.cluster.local:27017"
          - "--eval"
          - |
            rs.initiate({
              _id: "rs0",
              members: [
                { _id: 0, host: "{{ .Values.StatefulSet.name}}-0.{{ .Values.StatefulSet.service.name }}.{{ include "namespaceName" . }}.svc.cluster.local:27017" },
                { _id: 1, host: "{{ .Values.StatefulSet.name}}-1.{{ .Values.StatefulSet.service.name }}.{{ include "namespaceName" . }}.svc.cluster.local:27017" },
                { _id: 2, host: "{{ .Values.StatefulSet.name}}-2.{{ .Values.StatefulSet.service.name }}.{{ include "namespaceName" . }}.svc.cluster.local:27017" }
              ]
            });