apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitmq.name | default "rabbitmq" }}
  namespace: {{ include "namespaceName" . }}
  labels:
    app: {{ .Values.rabbitmq.name | default "rabbitmq" }}
    {{- include "spring-app.labels" . | nindent 4 }}
spec:
  serviceName: {{ .Values.rabbitmq.service.name | default "rabbitmq" }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name | default "rabbitmq" }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name | default "rabbitmq" }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.rabbitmq.image | default "rabbitmq:3.12-management" }}
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.defaultUser | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.defaultPass | quote }}
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-data
          emptyDir: {}
