apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.service.name | default "rabbitmq" }}
  namespace: {{ include "namespaceName" . }}
  labels:
    app: {{ .Values.rabbitmq.name | default "rabbitmq" }}
spec:
  ports:
    - port: 5672
      name: amqp
    - port: 15672
      name: management
  clusterIP: None
  selector:
    app: {{ .Values.rabbitmq.name | default "rabbitmq" }} 