apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecretName }}
  namespace: {{ include "namespaceName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson | quote }}
