apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.service.name }}
  namespace: {{ include "namespaceName" . }}
spec:
  selector:
    app: {{ .Values.labels.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.service.port }}
      targetPort: {{ .Values.deployment.service.targetPort }}
      {{- include "spring-app.nodePort" . | nindent 6 }}
  type: {{.Values.deployment.service.type }}


