apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ include "namespaceName" . }}
  labels:{{- include "spring-app.labels" . | nindent 4 }}
    
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      imagePullSecrets: 
        - name: {{ .Values.imagePullSecretName | quote }}
      containers:
        - name: {{ .Values.deployment.containerName }}
          image: {{ .Values.deployment.image }}
          ports: 
            - containerPort: {{ .Values.deployment.service.targetPort }}
              protocol: TCP
          env:
          - name: MONGO_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}  
                key: MONGO_HOST         
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: MONGO_PORT       
          - name: MONGO_DATABASE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}     
                key:   MONGO_DATABASE         
          - name: RABBITMQ_HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: RABBITMQ_HOST
          - name: RABBITMQ_PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: RABBITMQ_PORT
          - name: RABBITMQ_USERNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}     
                key: RABBITMQ_USERNAME         
          - name: RABBITMQ_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: RABBITMQ_PASSWORD
          - name: MEMCACHED_SERVERS
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: MEMCACHED_SERVERS
          resources:
            requests: 
              memory: {{ .Values.deployment.resources.requests.memory }}
              cpu: {{ .Values.deployment.resources.requests.cpu }}
            limits:
              memory: {{ .Values.deployment.resources.limits.memory }}
              cpu: {{ .Values.deployment.resources.limits.cpu }}


