apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.StatefulSet.service.name }}
  namespace: {{ include "namespaceName" . }}
spec:
  selector:
  {{- .Values.StatefulSet.labels | toYaml | nindent 6 }}
  ports:
    - protocol: TCP
      port: {{ .Values.StatefulSet.service.port }}
      targetPort: {{ .Values.StatefulSet.service.targetPort }}
      {{- include "spring-app.nodePort" . | nindent 6 }}
  type: {{.Values.StatefulSet.service.type }}




