---
- name: Ensure ~/.kube dir exists on Ansible controller
  hosts: localhost
  become: yes
  tasks:
    - name: Create .kube directory for ubuntu user
      file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
  roles:
    - docker_install



- name: Generate kubeadm init
  hosts: master
  become: true
  roles:
    - kubeadm_init

