---
- name: Ensure containerd config directory exists
  file:
    path: /etc/containerd
    state: directory

- name: Generate containerd default config and enable SystemdCgroup
  shell: |
    containerd config default | \
      sed -e 's/SystemdCgroup = false/SystemdCgroup = true/' \
          -e 's|sandbox_image = "registry.k8s.io/pause:3.6"|sandbox_image = "registry.k8s.io/pause:3.9"|' \
      > /etc/containerd/config.toml

- name: Restart containerd
  systemd:
    name: containerd
    state: restarted
    enabled: yes
